version: 2
registries:
  npm-npmjs:
    type: npm-registry
    url: https://registry.npmjs.org
    token: '${{secrets.NPM_TOKEN}}'
  npm-registry-npm-pkg-github-com-catchen:
    type: npm-registry
    url: https://npm.pkg.github.com/CatChen
<<<<<<< HEAD
    token: '${{secrets.GITHUB_TOKEN}}'
=======
    token: '${{secrets.NPM_GITHUB_TOKEN}}'
>>>>>>> 93fc92e (Providing token for public npm registry (#286))

updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '03:00'
      timezone: US/Pacific
    reviewers:
      - catchen
    assignees:
      - catchen
    registries:
      - npm-npmjs
      - npm-registry-npm-pkg-github-com-catchen
