language: node_js
install:
  - yarn install
node_js:
  - stable
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn build
  - yarn flow
  - yarn test src --coverage --collectCoverageFrom=src/** && yarn codecov -C
deploy:
  provider: npm
  email: cathsfz@gmail.com
  skip_cleanup: true
  api_key:
    secure: lGJZuykYo8aqLR/GT3Tydl1yVzL/zTULZ+V2+fert2Mg5vuEjlea8ZbvG739iIf/PHhiaS5NaL18zTLAaiLrrWZwdlptI3KkxBnpj26pDE42KCqi5qzYEfNe/7t6kbTkPSqc50ZF/BxNx7eDDMZzFcLfy+QVbBLpkSyicAX7EHqRaxrsELgsOV5beu/9631i2g2l/kjIP2HsONK4vlKJ0rhVypU20mb+GjD8Ffl/R6i36l+1IBSoe7/LX8Ck1R2u+lM72QzjvpDsxVvuTp8g5FEyaS5Fu4P8ENwj5/iDGIlvWnEpPabBPjCjuNMgXA4X5H4Bvman2ybnzVH39ekIz6+9p6rZnXPUp67OyVzsQXPNJxLehTn4dTTrvPHSIusM4bezA0nDgpeIR97u87seUMhfZulyq3B1TEJ05Ua9iypxIh/kw3+i0xq80Zf05cvnojyyeqg4373xLl3c79B07+RS0tRHlzC+emZQ4yNZ4SbKnHkeb9POoEbA9ivkcfFRkP8UydkCq3GEDlblb3Zl/yRuhGt9GCVr3ECnjSI1VMvnFkahwHXW93NC0d7KVsU/FNi115076uJE02Dl2Od2+qFFQV+hqwfxy1VOMM1qDo1XLB7BtJU3AnoEXPHj6cH4SZjhUbUX+KqLt9yOlk4TvQvdEDGNbEGQo3DZpQKdkUo=
  on:
    repo: CatChen/browser-id
    tags: true
