name: JSR Package

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: false
      dry-run:
        type: boolean
        default: false
        required: false

jobs:
  publish-jsr:
    name: Publish to JSR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/create-github-app-token@v2
        id: get-github-app-token
        with:
          app-id: ${{ secrets.CHECK_GIT_STATUS_BOT_APP_ID }}
          private-key: ${{ secrets.CHECK_GIT_STATUS_BOT_APP_PRIVATE_KEY }}
      - uses: CatChen/config-git-with-token-action@v2
        with:
          github-token: ${{ steps.get-github-app-token.outputs.token }}
      - uses: actions/checkout@v5
        if: ${{ !inputs.dry-run }}
        with:
          ref: ${{ inputs.tag }}
      - uses: actions/checkout@v5
        if: ${{ inputs.dry-run }}
        with:
          ref: ${{ github.ref_name || github.ref }}
      - uses: denoland/setup-deno@v2
        with:
          deno-version: latest
      - run: |
          # Hack for switching from using NPM to JSR
          cat src/browserID.ts | sed "s/'versioned-storage'/'@catchen\\/versioned-storage'/g" > src/browserID.deno.ts
          mv -f src/browserID.deno.ts src/browserID.ts
          git commit -am 'Switched to JSR'
      - run: |
          deno install
      - env:
          DRY_RUN: ${{ inputs.dry-run || false }}
        run: |
          if [[ "$DRY_RUN" = true ]]
          then
            deno publish --dry-run
          else
            deno publish
          fi
